title: kugouming - 酷狗明点滴人生
name: kugouming
email: mark@fback.com
description: 王明，网名kugouming，PHP工程师，从事web相关的开发工作。开源爱好者，GitHub:https://github.com/kugouming。
keywords: ""
skill_keywords: [PHP, Javascript, HTML+CSS, Linux, Laravel, Git, Mac, RESTful, Stackoverflow, Sublime Text, OmniGaffale, OminiPlan]

timezone:    PRC
encoding: "utf-8"

url: ""
baseurl:  "/"
domain:    ""
permalink:     /articles/:year/:month/:title.html
paginate_path: 'page:num'
paginate:   10
source_code: https://github.com/kugouming/kugouming.github.io

# Build settings
markdown:    kramdown
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

gems:
  - jemoji
  - rouge
  # # # - jekyll-mentions
  # - jekyll-sitemap
  - jekyll-html-pipeline

disqus:
  id: kugouming

google:
    analytics_id: UA-55452630-1

# navigation
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: https://github.com/kugouming
    label: GitHub
    target: _blank

  -
    href: http://weibo.com/2212486361
    label: Weibo
    target: _blank

  -
    href: /bookmark
    label: Bookmark

  -
    href: /about
    label: About

popular_repos: "" # ['pinyin', 'wechat', 'writor', 'laravel-wechat', 'laravel-lang', 'laravel-pinyin', 'latest-laravel', 'latest-lumen']
contribute_repos: "" #['laravel/framework', 'tymondesigns/jwt-auth', 'caouecs/Laravel-lang']
